title: “La Marseillaise” by Claude-Joseph Rouget de l’Isle
baseurl: /lilypond-piano-la-marseillaise
url: https://jeandeaual.github.io
repository: jeandeaual/lilypond-piano-la-marseillaise
lang: en-US
show_downloads: false
# Build settings
theme: jekyll-theme-minimal
plugins: []
defaults:
  - scope:
      path: "a4"
    values:
      a4: true
  - scope:
      path: "letter"
    values:
      letter: true
  - scope:
      path: "svg"
    values:
      svg: true
  - scope:
      path: "midi"
    values:
      midi: true
